[package]
name = "compiler"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
pest = "1.0.0-beta"
pest_derive = "1.0.0-beta"
core = { path = "../core" }
machine = { path = "../machine" }
